export const ADD_ROOM = 'ADD_ROOM'
export const ADD_FRIEND ='ADD_FRIEND'
export const FIND_FRIEND = 'FIND_FRIEND'
export const SET_USER = 'SET_USER';
export const DELETE_USER = 'DELETE_USER';
export const ENABLE_LOADER = 'ACTIVATE_LOADER';
export const DISABLE_LOADER = 'DISABLE_LOADER';
export const CREATE_ROOM = 'CREATE_ROOM'
export const DELETE_FRIEND_OUT = 'DELETE_FRIEND_OUT'
